### PR TITLE
Start HomeScreen redesign (WIP)

### PR DESCRIPTION
**Pull request by vfsfitvnm**
This is my attempt in redesigning the home scree (#11).
I need feedback :face_exhaling: 

Preview:

https://user-images.githubusercontent.com/46219656/179315841-4df5bdce-35bf-4b34-a350-171ff8e9a92c.mp4

[APK download](https://github.com/vfsfitvnm/ViMusic/suites/7380795505/artifacts/300103470)

### CODE REVIEW

**Comment by noClaps** [comment]
1. You should reduce or remove the delay between the screen shifting between the different sections and the indicator at the top reflecting it. It makes it seem like the app is lagging.
2. The audio player screen (the one with the song in fullscreen, as well as the Up Next and Lyrics) is very laggy while playing a song.
3. Opening the player screen (same one as above) is also very slow.
4. There should be some way to dismiss the currently playing song, either through a button in the corner or by swiping it away.
5. Bottom player should have more controls than just play/pause. Maybe add the skip forward/backward buttons too?
6. Album and artist images don't show up until I click on them. They should be loaded automatically.
7. I still believe you should get rid of the Cached feature, and implement a download feature instead. It shouldn't be too functionally different, since you're able to listen to songs offline either way, but making it optional would help those who don't have that much phone storage, or those who simply want a streaming solution. Plus, not everyone knows what a cache is, but most people know what a download is, so it would help that way too. You could also rename it to something else, like "Offline" or "Saved".

**Comment by Jak2k** [comment]
I think the advantage of the previous home screen was that you can the everything at the same time. The advantage of the new is that it's mire clear. Maybe you could add a tab in the new home screen where it's possible to access the old.

**Comment by vfsfitvnm** [comment]
@noClaps 

I was looking for feedbacks regarding the layout redesign to be honest, however:

1. Yes. I'll do that. It is harder than it looks, that's why I left it for last.
2. This is a debug build, that's why it lags.
3. Same as 2.
4. #51
5. #79 
6. I don't have such information when I store an artist or album to the database - I just have its name and id. I don't feel like I should do an extra network request just for the thumbnail (the same applies to albums).
7. I think the caching is essential. This is what other apps don't have - all I see is people complaining about their network plan fade away because of this. You can't be mad about 512MB of space occupied, but fine with GBs of network requests. Doing network requests is expensive, introduces delays and drains your battery faster.

@Jak2k

We already have a contrasting opinion. I do agree it is useless to display albums and artists in a dedicated tab. Maybe I could implement something like [this](https://dribbble.com/shots/15061131-Music-Player-App-Interactive-Prototype), where artists have their row at the top.

**Comment by C2M6D** [comment]
Looks pretty good. I like that you have implemented the artists and album tabs. I also wanted to add that I think the cached feature is better than a dowload feature, as plenty of other apps and services already offer this,whereas a cached feature is just a good data and battery saver. If I would want to dowload a song, I just share it directly to NewPipe, and dowload it via NewPipe. 
All in all, I think this new hone layout is relatively clean and suits the aesthetic of the app. I felt that the old home screen was a bit too minimal, but this is very much a nice redesign.

**Comment by noClaps** [comment]
@vfsfitvnm 

For the caching thing, what I meant to say was to get rid of the Cached playlist. Caching by itself is completely fine, afaik Spotify and other music streaming apps do it too, so that the music doesn't stop immediately if internet goes out. However, what you've done is attempted to replace offline play with a cache, which I'm assuming would reset if i restart my phone. Wouldn't that defeat the purpose of having offline play and data saving if I'm having to save the songs each time my phone reboots?

Implementing a proper download feature is up to you though. It'd be nice to have, but not really a deal-breaker if its not there.

As for the album and artist covers, it's just something that would make it look nicer. You can see the names so I suppose its not a huge deal, but having the album covers there would certainly help. I usually recognise albums by their cover much more quickly and accurately by their covers rather than their names, which is why it not showing up automatically really stood out to me.

Other than that, I think the redesign overall looks great, and much better and more polished than what the app was previously.

**Comment by vfsfitvnm** [comment]
@noClaps 

The cache is persistent, i.e. it survives device reboots or whatever. That's the purpose of a cache - having a playlist whose songs can be played offline. The difference between the current cache system and a download feature is where and how the song is stored - that's it. Downloading (what the average user understand as _downloading_) requires exporting the song to the user storage so it can have the actual file on hands.

I have been a YMusic user, and I honestly **hated** the lack of a cache system. If I wanted to play a song I already listened to without a network connection, I had to explicitly download it.
YouTube Music (and Spotify?) behaves the same as YMusic - its cache is temporary and it is freed up when the app restarts or the device is rebooted. Completely useless.

I agree I should rename that built-in playlist to something else, your suggestions "Offline" fits better.

Regarding the album/artists thumbnails, unfortunately there isn't much I can do yet.

**Comment by nateRiver111** [comment]
Could you implement a search feature in the cached playlist with all available songs indexed so it can be used offline

**Comment by Surendrajat** [comment]
While the redesign follows the typical/popular music app layout and I understand the appeal, to me though it's a regression in a way. I quite like the current minimalist design and the UX.
As you've already noted, singer and album views aren't as important as songs and playlist, since you rarely like all the songs from a singer/album. And the one you really like, you add those to a playlist or simply find them in songs list. Besides, accessing album/singer is currently just 2 actions away(long press on song + click `More of ...` or `Go to album`) and redesign doesn't change this(right swipe gesture 1-3 times + click on singer/album).

I used to be a [Blackhole](https://github.com/Sangwan5688/BlackHole) contributor/user but switched to ViMusic right away because of this minimalistic design and no feature-creep. So while I feel like this redesign is going to happen, I do hope it doesn't end up being yet another full-featured music app.

Oh and btw, thanks for the app. ViMusic is now the go-to music app for me and my friends :)

**Comment by noClaps** [comment]
@vfsfitvnm 

> The cache is persistent, i.e. it survives device reboots or whatever. That's the purpose of a cache - having a playlist whose songs can be played offline.

Ah, okay. You see, that was confusing me since generally when I think of cache, I think of the [general computing term](https://en.wikipedia.org/wiki/Cache_(computing)), which is where data is stored in memory to help speed up future data requests. It's not necessarily an "available offline" thing, more of a speed thing. I'm used to hearing about cache being cleared when the app is closed or device rebooted. Maybe that's just me. I think renaming it to "Offline" will certainly help with clarity.

> YouTube Music (and Spotify?) behaves the same as YMusic - its cache is temporary and it is freed up when the app restarts or the device is rebooted.

Those apps don't export the songs into external storage when they "download" the songs. All that downloading means is that the file (a song in this case) is available offline, though not necessarily accessible to the end-user. However, I agree with your point that it can be confusing someone who expects to get MP3s when they click download.

> If I wanted to play a song I already listened to without a network connection, I had to explicitly download it.

Well, that's kind of the point. Those apps are meant for streaming music online, with allowing the songs to be available offline as a secondary feature. By creating a permanent cache, what you've essentially created is an app that downloads and plays music, with streaming as a secondary feature. If that's the direction you're looking to take your app, then go for it. However, if you're trying to make a "traditional" music streaming app, then an default 0.5GB permanent cache isn't really the best way to go, in my opinion.

Also may I suggest using the Discussions feature for this instead of PR comments. It'll help keep things nice and organised.

**Comment by vfsfitvnm** [comment]
@Surendrajat 
Thank you for sharing your thoughts.

I think we should try to pick the best of the two layouts.

Considering the current layout, I don't like how its code is structured (this is also a problem of every other screen), but it's shorter. The candidate layout code feels better organized, but it's longer and more complex (and also crashed one time due to a Jetpack Compose bug).

I still think having a dedicated tab for artists and albums is pointless (I agree with what @Surendrajat said regarding this), but I do also agree with @noClaps about the feel of being more organized.
But we can't ignore the fact a thumbnail won't be displayed until the artist or album page is visited. This is another drawback of having the artist/album page (well, I could just display items which have a thumbnail, but then people will complain about not being able to view the full list).
If you really like an album, you can quickly import it as playlist. Regarding the artists, I could add a very simple "pin"/"like" system, and these artists will be displayed on the row I mentioned before (if you don't have any pinned artist, the row won't appear).

However, I'm not sure how to move now.

@noClaps 

Yes, I should have used "disk cache" instead of a general "cache" term, which can me ambiguous and misinterpreted for a "memory cache". However, from now on "disk cache" is intended when I write "cache".

> By creating a permanent cache, what you've essentially created is an app that downloads and plays music, with streaming as a secondary feature.

This is misleading. ViMusic does not download and plays music (if it would, it would take seconds to start the playback), but it streams music and it progressively saves it on disk. When I listen to a song, chances are I'll probably listen to it again sooner or later. If this happens "sooner", I will save energy and battery. That's it.

**Comment by vfsfitvnm** [comment]
Regarding the discussions tab, I already made the mistake of enabling it in another repository of my own. People will eventually use it to report bugs, and use the issue tracker to ask questions

**Comment by noClaps** [comment]
> ViMusic does not download and plays music (if it would, it would take seconds to start the playback), but it streams music and it progressively saves it on disk.

Right, so it downloads and plays music simultaneously. That's functionally what Spotify and YT Music do, just not by default. My issue with this feature isn't its presence, its the fact that it's enabled by default and for all songs. I'm actually very supportive of the fact that you've implemented an offline listening option. But having the feature be optional and off by default, and configurable by playlist, similar to how traditional apps do it, might be better. Maybe a toggle in the playlist view and/or Songs tab?However, it's up to you how you want to implement it.

> When I listen to a song, chances are I'll probably listen to it again sooner or later.

When you have a list of songs in the hundreds, the storage size increases to 10s of GBs, and the chances that you hear a song frequently are relatively low, especially if you shuffle play. I get your point, but just from my own experience, it would cause the same storage space issues that I'm already having.

> Regarding the discussions tab, I already made the mistake of enabling it in another repository of my own. People will eventually use it to report bugs, and use the issue tracker to ask questions

You can moderate that however you like. Make Contribution guidelines and enforce them. Plus, GitHub provides a feature to allow you to convert issues into discussions. Up to you, it was just a suggestion.

> You can't be mad about 512MB of space occupied, but fine with GBs of network requests. Doing network requests is expensive, introduces delays and drains your battery faster.

But if you're streaming while caching, wouldn't you be doing both GBs of space as well GBs of network requests, especially with a large number of songs? Sure, it's only once for the network requests, but it still happens. In my experience, I've seen more people who have issues with storage space than with data usage. I've also noticed that streaming doesn't take nearly as much as downloading, or caching as you call it, does. I've personally used Spotify for months, with my data usage by it not going over like 2-3 GB. This is with me listening for a few hours every single day. Compared to that, my downloaded songs, in total, take up ~10GB of space, which would be equivalent in data usage I assume.

At the end of the day, it's up to you what features you want to implement in your app, I'm simply throwing out ideas.

**Comment by Surendrajat** [comment]
> Regarding the artists, I could add a very simple "pin"/"like" system, and these artists will be displayed on the row I mentioned before (if you don't have any pinned artist, the row won't appear).

Sounds like a good approach

> Considering the current layout, I don't like how its code is structured...

I feel that UX is slightly more important than code structure :)

> However, I'm not sure how to move now.

Take your time… Mark the PR draft or something and experiment maybe. I think people will appreciate a well-thought-out design, albeit late.

**Comment by vfsfitvnm** [comment]
@noClaps 

Basically you want a similar thing of #74.

I believe music is temporary. That is I stick with an artist, a genre or a song for a period of time (a couple of days, one week, three months, one year) and then I just move on. It doesn't mean I only listen to few songs,  but those few songs are the "cornerstones".
You know, music accompany our life, so it reflects our moods and what happen to us. That's why it is temporary, life changes and so the music. Yes, I will still listen to song I previously enjoyed from time to time in the future, but it won't be my primary focus - my taste or life moved on.
I don't have a "all time favorites" playlist which I listen to regularly, because I already know it won't be listenable because it is too diversified.

I don't know how you listen to music, but I doubt you listen to e.g. 100 new songs every single day and never stick with any. This is not what I had in mind when I created ViMusic - it's not a "music zapping" app. This is also a reason why I didn't implement the "Explore" tab yet.

**How does this matter with the cache?**

From my point of view, a manual cache is inconvenient.
When I switch to another set of songs, I'd have to carefully cache these songs before I play them for the first time.
When the radio is playing, I'd have to stop what I am doing to open the app and make sure to "save" the song I'm listening to, if I like it.
What about songs I don't like too much to be saved (or remembered) but they aren't too bad to be skipped?

These are already three huge disgraces for me.

An automatic cache (with LRU strategy) solves every problem.
From a user point of view, I think it is more user friendly, because of the three points above. However, I understand it may be inconvenient **only** if you listen to 8GB (~132 hours of playback) of new, different songs and then you switch back to the 20, 50 songs you periodically listen to.
From a technical point of view, the only drawback I can think of is disk space waste - for e.g. when you listen to a song you hate. But wasting disk space is infinitely better than wasting bandwidth and battery - this is not an opinion.
From a coding point of view, it is way simpler to implement.

**Comment by noClaps** [comment]
Alright, no worries. I guess I'll keep looking for something that fits my use case.

Cheers!

P.S. I ask you to reconsider using the Discussions feature. It makes discussions like this more organised, rather than having a conversation about caching in a PR for UI (my bad for that btw, sorry).

**Comment by BluePixel4k** [comment]
It was a bit tedious to fight through the comments. 😉 
But I would like to share my thoughts about the presented design. 

I think its a good way, but I have some suggestions, particular for the main tab.

I think a merge of both layouts would be perfect. 

---

Fo me, I like it, if I could use the home screen as an "inspiration" page. 
So its would be nice, if the I can see last played radios, playlists or albums there.

In relation to #36, it would be nice to get some suggest playlists, but as you say you don't want to implement a explore function for now:
> I don't know how you listen to music, but I doubt you listen to e.g. 100 new songs every single day and never stick with any. This is not what I had in mind when I created ViMusic - it's not a "music zapping" app. This is also a reason why I didn't implement the "Explore" tab yet.

But maybe the app could suggest me radios from my favorite most played songs, to get to know new songs?

---

Under the categories songs and playlists I would only show titles that are in saved playlists / you have liked. Otherwise the pages become too quickly confusing.
Under the last played songs you can furthermore see played songs which you would like to hear again.

Its getting a little tricky, but:
- under albums, I would only show these albums who I played consciously
- or if I saved maybe minimum 3(?) songs of an album, it can show the full album in this section

---

>>> We already have a contrasting opinion. I do agree it is useless to display albums and artists in a dedicated tab. Maybe I could implement something like [this](https://dribbble.com/shots/15061131-Music-Player-App-Interactive-Prototype), where artists have their row at the top.
>>
>> Having a single row for all the artists works when its in the "Top Artists" style, if there's only 4-5 there.
>
> Regarding the artists, I could add a very simple "pin"/"like" system, and these artists will be displayed on the row I mentioned before (if you don't have any pinned artist, the row won't appear).

That's looks great for the home screen! Only show a few of my top artists or to add a "pin"/"like" feature sound like a good solution.

---

> An automatic cache (with LRU strategy) solves every problem.

How difficult is it to implement a LRU feature to clear the cache from old songs? 
Or what happens, if the current cache limit is reached?

---

It's a lot of text, unfortunately, but maybe it helps. 😇

**Comment by faustaahmad** [comment]
> While the redesign follows the typical/popular music app layout and I understand the appeal, to me though it's a regression in a way. I quite like the current minimalist design and the UX.
....

I agree with that statement, I like current design too
It's unique, minimalist, and straightforward
Just scroll a bit & you already found the songs/playlist (my song's list still small)

Sadly, I don't know anything about this
> Considering the current layout, I don't like how its code is structured...

Overall, redesign theme is similar current design (List) merged with default Tab material theme, Nice

**Here some of my suggestions & opinions:**
1. Options to Hide some Tab (`Songs`, `Playlists`, `Artists`, `Albums`)
> I don't have such information when I store an artist or album to the database - I just have its name and id. I don't feel like I should do an extra network request just for the thumbnail (the same applies to albums).

2. Ability to store any cover (including artist & album) into disk cache (?)
3. Something like this, instead of plain ViMusic text in top left corner
| **Songs** Playlists Artists Albums ⌕ ⋮ |
   - **Bold, Big title**: Current Tab
   - Fade, Small title: Other Tab
4. ~~Theme~~, Accents
5. Ability to change player's bar or progress bar color depends on song's cover
6. I shouldn't ask this here, but
   - Bulk deletion
   - Custom cover (any)
   - Custom Volume control (usually I play music while doing another thing, but music sometimes too loud that I cant even hear sfx sound)

**Comment by Alliba** [comment]
I like it.

**Comment by Alliba** [comment]
I like it.

**Comment by Alliba** [comment]
> This is my attempt in redesigning the home scree (#11). I need feedback 😮‍💨
> 
> Preview:
> 
>  untitled.mp4 
> [APK download](https://github.com/vfsfitvnm/ViMusic/suites/7380795505/artifacts/300103470)

please quickly update to the normal APP. I find it 

much easier and clearer to use.

**Comment by vfsfitvnm** [comment]
Thanks for the feedback.

However, I will redesign the whole UI sooner or later. Things can't just expand vertically. The current layout is fine, but it's **very** limiting when it comes to adding resources.  As long as I leave things as they are, I can't implement #36, #123.

##### You may have won this battle, but not the war (yet). :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
