### PR TITLE
Implemented multilingual support

### PR DESCRIPTION
**Pull request by fast4x**
Default language is English, Italian, Spanish, French and German have been added.

Other languages can be added in the future.

### CODE REVIEW

**Comment by fast4x** [comment]
Some images of ViMusic in Italian language

**Comment by LoVega1337** [comment]
This is a good change, but I'd go with only English for now and remove the other language's XML. I've gone through the German one as an example and it literally is just non-sense, I would assume it's just Google Translate without context. I guess this is the same for the other languages.

I would let native speakers put up further PRs for their language, noone is happy with Google translated strings.

**Comment by fast4x** [comment]
Italian is a native speaker, so it can be entered. 
For the others i have not used Google so it may be that they are not 100% correct. You can always ask native-speaking collaborators to translate other languages better than English and Italian.

**Comment by LoVega1337** [comment]
Yes exactly, for that reason I wouldn't include German/Spanish/French in this PR and let other people submit their languages.

**Comment by fast4x** [comment]
Thanks for the appreciation

**Comment by fast4x** [comment]
@vfsfitvnm 
I found your comment about localization 
https://github.com/vfsfitvnm/ViMusic/pull/171#issuecomment-1206528846
Unfortunately I had not read it before submitting my pull request.
Sorry, closing my pull request.

**Pull request closed without merging**
