### PR TITLE
This is people file

### PR DESCRIPTION
**Pull request by Rashtra04**

### CODE REVIEW

**Review by ikanakova — COMMENTED** [review]
I can't believe someone's spamming like this.
Edit: The fact that someone can post such pull requests here with completely nonsensical things and they are still open proves that @vfsfitvnm has completely abandoned this application.

**Comment by mayankmbm** [comment]
The search button irritates me a lot
Click on search icon at bottom
And type at the top
Really frustrating... I'm not even a tech guy I just made github id for this complaint 😬

**Comment by ikanakova** [comment]
> The search button irritates me a lot Click on search icon at bottom And type at the top Really frustrating... I'm not even a tech guy I just made github id for this complaint 😬

@mayankmbm Issues are for suggestions and bugs, pull requests are for who knows how to program to add a function!

**Comment by DarkCrypt** [comment]
> abandoned

It sure looks like it. The app has been in "maintenance mode" for months but this was never stated in the README.

**Pull request closed without merging**
