### PR TITLE
add screenshots in a table

### PR DESCRIPTION
**Pull request by meanindra**
Screenshots are now better visible in GitHub mobile app and mobile browser
### Before
photo_2022-07-18_18-26-03
### After
photo_2022-07-18_18-25-59

### CODE REVIEW

**Comment by vfsfitvnm** [comment]
Thanks, is there a way to hide the grid borders?
Also, make sure to capitalize the first letter of the commit message

**Comment by meanindra** [comment]
> is there a way to hide the grid borders?

Unfortunately it is not possible to hide markdown table borders
https://stackoverflow.com/questions/63664726/how-to-get-rid-of-table-borders-in-markdown

> make sure to capitalize the first letter of the commit message

Ok

**Comment by VedxP** [comment]
Screenshot_2022-07-22-20-42-16-55_40deb401b9ffe8e1df2f1cc5ba480b12

@vfsfitvnm This layout?

**Comment by meanindra** [comment]
> ![Screenshot_2022-07-22-20-42-16-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/87353286/180469844-2ffe850c-855c-4d5a-93c5-9b9039e2b10e.jpg

Nice 👍

**Comment by vfsfitvnm** [comment]
Implemented in #115 - thanks @VedxP and @meanindra

**Pull request closed without merging**
